# Generated by Django 3.0.6 on 2021-01-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20210107_2030'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
