# Generated by Django 3.0.6 on 2020-12-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201225_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='box_size',
            field=models.CharField(choices=[('50х50х35', '50х50х35'), ('60х60х40', '60х60х40'), ('60х60х40-P', '60х60х40-P'), ('80х80х40', '80х80х40'), ('80х80х40-P', '80х80х40-P'), ('240х185х120', '240х185х120'), ('270х220х70', '270х220х70')], default='80х80х40', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=None, null=True),
        ),
    ]
