# Generated by Django 3.1.3 on 2020-12-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201223_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='lives_in',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='nick_name',
        ),
        migrations.AddField(
            model_name='friend',
            name='tirazh',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
