# Generated by Django 3.0.6 on 2020-12-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201227_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Detail Text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainimage',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview_text',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Preview Text'),
        ),
    ]
