# Generated by Django 3.1.3 on 2021-01-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210106_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='timedelta',
            new_name='t',
        ),
    ]
