# Generated by Django 3.1.3 on 2021-01-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210106_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='t',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
