# Generated by Django 3.1.3 on 2021-01-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210106_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='t',
            field=models.DateField(auto_now_add=True),
        ),
    ]
