# Generated by Django 3.0.6 on 2021-01-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210107_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='box_size',
            field=models.CharField(choices=[('270х220х70', '270х220х70')], default='80х80х40', max_length=20),
        ),
    ]
