# Generated by Django 3.1.3 on 2021-01-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210108_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='k',
            field=models.IntegerField(null=True),
        ),
    ]
