# Generated by Django 3.1.3 on 2021-01-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_k'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.AddField(
            model_name='category',
            name='preview_text',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Preview Text'),
        ),
    ]
