# Generated by Django 3.1.3 on 2021-01-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20210113_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='preview_text',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='Preview Text'),
        ),
    ]
