# Generated by Django 3.1.3 on 2021-01-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_subcategory_preview_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wanted',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='wanted'),
        ),
    ]
