# Generated by Django 3.1.3 on 2021-01-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_product_wanted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wanted',
        ),
    ]
