# Generated by Django 3.0.6 on 2021-01-19 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20210119_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderType2',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('products.product',),
        ),
        migrations.AlterField(
            model_name='product',
            name='box_size',
            field=models.CharField(choices=[('50х50х35', '50х50х35'), ('60х60х40', '60х60х40'), ('60х60х40-P', '60х60х40-P'), ('80х80х40', '80х80х40'), ('80х80х40-P', '80х80х40-P'), ('240х185х120', '240х185х120'), ('270х220х70', '270х220х70'), ('корешок 25-40 круглый механизм 7200', 'корешок 25-40 круглый механизм 7200'), ('корешок 45-65 д-образный механизм', 'корешок 45-65 д-образный механизм')], default='80х80х40', max_length=50),
        ),
    ]
