# Generated by Django 3.1.3 on 2021-02-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20210201_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview_text',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='Preview Text'),
        ),
    ]
