# Generated by Django 3.1.3 on 2021-02-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20210201_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='box_size',
            field=models.CharField(choices=[('50х50х35', '50х50х35'), ('60х60х40', '60х60х40'), ('80х80х40', '80х80х40'), ('240х185х120', '240х185х120'), ('270х220х70', '270х220х70')], default='80х80х40', max_length=50),
        ),
    ]
