# Generated by Django 3.1.3 on 2021-02-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_boxsizes_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='k',
            field=models.FloatField(default=None, null=True),
        ),
    ]
