# Generated by Django 3.1.3 on 2021-02-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20210202_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='box_size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview_text',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Preview Text'),
        ),
    ]
