# Generated by Django 3.1.3 on 2021-02-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_auto_20210203_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
