# Generated by Django 3.1.3 on 2021-02-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lim1',
            field=models.IntegerField(null=True),
        ),
    ]
