# Generated by Django 3.1.3 on 2021-02-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_product_lim1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lim1',
            field=models.FloatField(default=None, null=True),
        ),
    ]
