# Generated by Django 3.1.3 on 2021-02-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_auto_20210209_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxsizes',
            name='mainimage',
        ),
        migrations.AddField(
            model_name='boxsizes',
            name='d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boxsizes',
            name='h',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
