# Generated by Django 3.1.3 on 2021-02-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_auto_20210210_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='k',
            new_name='p',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lim1',
        ),
    ]
