# Generated by Django 3.1.3 on 2021-02-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_auto_20210210_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsizes',
            name='TEST',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
