# Generated by Django 3.1.3 on 2021-02-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_boxsizes_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxsizes',
            name='TEST',
        ),
        migrations.RemoveField(
            model_name='boxsizes',
            name='k',
        ),
        migrations.RemoveField(
            model_name='boxsizes',
            name='lim1',
        ),
        migrations.RemoveField(
            model_name='boxsizes',
            name='lim2',
        ),
        migrations.AddField(
            model_name='product',
            name='lim1',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lim2',
            field=models.FloatField(default=None, null=True),
        ),
    ]
