# Generated by Django 3.1.3 on 2021-02-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_auto_20210215_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsizes',
            name='e',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
