# Generated by Django 3.1.3 on 2021-02-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_boxsizes_e'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxsizes',
            name='e',
        ),
    ]
